// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagementAPI.Data;

#nullable disable

namespace TaskManagementAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920175918_AddTaskAuditLog")]
    partial class AddTaskAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagementAPI.Models.TaskAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskAuditLogs");
                });

            modelBuilder.Entity("TaskManagementAPI.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToUserId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configure GitHub Actions for build and test.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            RowVersion = new byte[0],
                            Status = "Done",
                            Title = "Set up CI pipeline"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToUserId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Model tasks, users, and relationships.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Critical",
                            RowVersion = new byte[0],
                            Status = "Done",
                            Title = "Design database schema"
                        },
                        new
                        {
                            Id = 3,
                            AssignedToUserId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CRUD endpoints for tasks with filtering.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            RowVersion = new byte[0],
                            Status = "InProgress",
                            Title = "Implement task API endpoints"
                        },
                        new
                        {
                            Id = 4,
                            AssignedToUserId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "React pages for authentication.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Critical",
                            RowVersion = new byte[0],
                            Status = "InProgress",
                            Title = "Build login and signup UI"
                        },
                        new
                        {
                            Id = 5,
                            AssignedToUserId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Issue and validate bearer tokens.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Critical",
                            RowVersion = new byte[0],
                            Status = "InProgress",
                            Title = "Add JWT authentication"
                        },
                        new
                        {
                            Id = 6,
                            AssignedToUserId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cover filtering and sorting logic.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Medium",
                            RowVersion = new byte[0],
                            Status = "ToDo",
                            Title = "Write unit tests for TaskService"
                        },
                        new
                        {
                            Id = 7,
                            AssignedToUserId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Colour-code priority in the UI.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            RowVersion = new byte[0],
                            Status = "ToDo",
                            Title = "Style task table with priority badges"
                        },
                        new
                        {
                            Id = 8,
                            AssignedToUserId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-stage build for deployment.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Low",
                            RowVersion = new byte[0],
                            Status = "ToDo",
                            Title = "Set up Dockerfile for API"
                        },
                        new
                        {
                            Id = 9,
                            AssignedToUserId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Document how to run API and frontend.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Medium",
                            RowVersion = new byte[0],
                            Status = "ToDo",
                            Title = "Write README setup instructions"
                        },
                        new
                        {
                            Id = 10,
                            AssignedToUserId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Investigate intermittent failure in CI.",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            RowVersion = new byte[0],
                            Status = "ToDo",
                            Title = "Fix flaky summary endpoint test"
                        });
                });

            modelBuilder.Entity("TaskManagementAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@example.com",
                            Name = "Demo User",
                            PasswordHash = "$2a$11$v031RUj/qYLCCV9cimQLuuyPP4Yr9wTl1wVr4UPAD2XsobNyZoLSy"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.chen@example.com",
                            Name = "Alice Chen",
                            PasswordHash = "$2a$11$v031RUj/qYLCCV9cimQLuuyPP4Yr9wTl1wVr4UPAD2XsobNyZoLSy"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.martinez@example.com",
                            Name = "Bob Martinez",
                            PasswordHash = "$2a$11$v031RUj/qYLCCV9cimQLuuyPP4Yr9wTl1wVr4UPAD2XsobNyZoLSy"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "priya.nair@example.com",
                            Name = "Priya Nair",
                            PasswordHash = "$2a$11$v031RUj/qYLCCV9cimQLuuyPP4Yr9wTl1wVr4UPAD2XsobNyZoLSy"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "diego.ruiz@example.com",
                            Name = "Diego Ruiz",
                            PasswordHash = "$2a$11$v031RUj/qYLCCV9cimQLuuyPP4Yr9wTl1wVr4UPAD2XsobNyZoLSy"
                        });
                });

            modelBuilder.Entity("TaskManagementAPI.Models.TaskAuditLog", b =>
                {
                    b.HasOne("TaskManagementAPI.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("TaskManagementAPI.Models.TaskItem", b =>
                {
                    b.HasOne("TaskManagementAPI.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");
                });
#pragma warning restore 612, 618
        }
    }
}
